{
  "openapi": "3.0.1",
  "info": {
    "title": "Users API",
    "version": "v1"
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "paths": {
    "/bets": {
      "get": {
        "summary": "Fetch all bets for the authenticated user",
        "tags": [
          "Bets"
        ],
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ],
        "responses": {
          "200": {
            "description": "Bets retrieved successfully"
          },
          "401": {
            "description": "Unauthorized request"
          }
        }
      },
      "post": {
        "summary": "Creates a new bet",
        "tags": [
          "Bets"
        ],
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ],
        "parameters": [

        ],
        "responses": {
          "201": {
            "description": "Bet created"
          },
          "422": {
            "description": "Unprocessable entity"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "amount": {
                    "type": "number"
                  },
                  "odds": {
                    "type": "number"
                  },
                  "event_id": {
                    "type": "string"
                  },
                  "predicted_outcome": {
                    "type": "string"
                  }
                },
                "required": [
                  "amount",
                  "odds",
                  "event_id",
                  "predicted_outcome"
                ]
              }
            }
          }
        }
      }
    },
    "/users/{user_id}/bets": {
      "get": {
        "summary": "Returns a user's bets",
        "tags": [
          "Bets"
        ],
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ],
        "parameters": [
          {
            "name": "user_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns user's bets"
          }
        }
      }
    },
    "/events": {
      "get": {
        "summary": "List all events",
        "tags": [
          "Events"
        ],
        "responses": {
          "200": {
            "description": "events retrieved"
          }
        }
      },
      "post": {
        "summary": "Create a new event",
        "tags": [
          "Events"
        ],
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ],
        "parameters": [

        ],
        "responses": {
          "201": {
            "description": "event created"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "start_time": {
                    "type": "string",
                    "format": "date_time"
                  },
                  "odds": {
                    "type": "number"
                  },
                  "status": {
                    "type": "string"
                  },
                  "result": {
                    "type": "string",
                    "nullable": true
                  }
                },
                "required": [
                  "name",
                  "start_time",
                  "odds",
                  "status"
                ]
              }
            }
          }
        }
      }
    },
    "/events/{id}": {
      "get": {
        "summary": "Show a specific event",
        "tags": [
          "Events"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID of the event",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "event retrieved"
          },
          "404": {
            "description": "event not found"
          }
        }
      },
      "put": {
        "summary": "Update an event",
        "tags": [
          "Events"
        ],
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID of the event",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "event updated"
          },
          "404": {
            "description": "event not found"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "start_time": {
                    "type": "string",
                    "format": "datetime"
                  },
                  "odds": {
                    "type": "number"
                  },
                  "status": {
                    "type": "string"
                  },
                  "result": {
                    "type": "string"
                  }
                },
                "required": [
                  "name",
                  "start_time",
                  "odds",
                  "status",
                  "result"
                ]
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete an event",
        "tags": [
          "Events"
        ],
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID of the event",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "event deleted"
          },
          "404": {
            "description": "event not found"
          }
        }
      }
    },
    "/events/{id}/update_result": {
      "patch": {
        "summary": "Update result of an event",
        "tags": [
          "Events"
        ],
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID of the event",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "result updated successfully"
          },
          "422": {
            "description": "cannot update result if event is not completed"
          },
          "404": {
            "description": "event not found"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "result": {
                    "type": "string",
                    "enum": [
                      "win",
                      "lose",
                      "draw",
                      "penalty"
                    ]
                  }
                },
                "required": [
                  "result"
                ]
              }
            }
          }
        }
      }
    },
    "/leaderboard": {
      "get": {
        "summary": "Retrieve the leaderboard",
        "tags": [
          "Leaderboard"
        ],
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ],
        "responses": {
          "200": {
            "description": "leaderboard retrieved"
          },
          "401": {
            "description": "unauthorized"
          }
        }
      }
    },
    "/results": {
      "get": {
        "summary": "Get all possible result types",
        "tags": [
          "Results"
        ],
        "responses": {
          "200": {
            "description": "results retrieved successfully"
          }
        }
      }
    },
    "/signup": {
      "post": {
        "summary": "User Signup",
        "tags": [
          "Users"
        ],
        "parameters": [

        ],
        "responses": {
          "201": {
            "description": "user created"
          },
          "422": {
            "description": "unprocessable entity"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "user": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "type": "string"
                      },
                      "email": {
                        "type": "string"
                      },
                      "password": {
                        "type": "string"
                      },
                      "password_confirmation": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "name",
                      "email",
                      "password",
                      "password_confirmation"
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/login": {
      "post": {
        "summary": "User Login",
        "tags": [
          "Users"
        ],
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "login successful"
          },
          "401": {
            "description": "unauthorized"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                },
                "required": [
                  "email",
                  "password"
                ]
              }
            }
          }
        }
      }
    },
    "/profile": {
      "get": {
        "summary": "Get User Profile",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ],
        "responses": {
          "200": {
            "description": "profile retrieved"
          },
          "401": {
            "description": "unauthorized"
          }
        }
      },
      "put": {
        "summary": "Update User Profile",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ],
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "profile updated"
          },
          "422": {
            "description": "unprocessable entity"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "user": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "type": "string"
                      },
                      "email": {
                        "type": "string"
                      },
                      "password": {
                        "type": "string"
                      },
                      "password_confirmation": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "name",
                      "email"
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete User Account",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ],
        "responses": {
          "200": {
            "description": "account deleted"
          },
          "401": {
            "description": "unauthorized"
          }
        }
      }
    }
  },
  "security": [

  ]
}